### PR TITLE
fix for very specific event subscriptions

### PR DESCRIPTION
**Pull request by abanchev**

### CODE REVIEW

**Comment by Flippo24** [comment]
It's been a long time since I worked with javascript. Can you describe me which error your change corrects? With this.series[product] the corresponding series is selected. Where does the replacing 'product' come from?

**Comment by Kir-SA** [comment]
this.series[product] does not have a "Product" property. A "current" event with specified product or product and timeframe will never fire because emitted event looks like "current undefined 1m".

**Comment by Flippo24** [comment]
The product property is now set correctly. Thank you both.

**Comment by Flippo24** [comment]
The product property is now set correctly. Thank you both.

**Pull request closed without merging**
